on:
  push:
    branches:
      - main
    paths:
      - '**.toml'
  workflow_dispatch:

jobs:
  elastic-detections-update:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: Run Update Script
        env:
          ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          python development/update_alert.py