name: Updating detections

on:
  push:
    path:
      '**.toml'
  workflow_dispatch:

jobs:
  elastic-detections-update:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v3

      - name: Run Update Script
        env:
          ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run:
          python development/update_alert.py