name: TOML/MITRE Validation

on:
  push:
    path:
      - 'detections/**.toml'
  workflow_dispatch:

jobs:
  toml-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: python development/validation.py
      - run: python development/mitre_from_git.py